name: Build-Action
description: 'build and push to ghcr'

inputs:
  PAT:
    description: 'PAT from repo'
    required: true
  NAMESPACE:
    description: 'Namespace'
    required: true
  NAME:
    description: 'Name'
    required: true
  ACTION_ENABLE_TESTING:
    description: 'if set to true, testcontainer will be created and tests will be run'
    required: false
    default: 'false'
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  ACTIVATE_DEV_RUNNER:
    description: 'if set to true, devRunner container will be created'
    required: false
    default: 'false'
  LOCAL_TESTING_SECRET:
    description: 'local-testing.yaml secret'
    required: false
    default: 'false'
  WORKING_DIRECTORY:
    description: 'Working directory of the project'
    required: false
    default: '.'
  TESTING_WITH_DB:
    description: 'if set to true, a database will be created and the tests will be executed'
    required: false
    default: 'false'
  DB_CREATE_FILEPATH:
    description: 'path to the database file'
    required: false
    default: '.'
  DB_TESTDATA_FILEPATH:
    description: 'path to the testdata file'
    required: false
    default: 'false'

outputs:
  version:
    description: 'version of the container'
    value: ${{ steps.set-output.outputs.version }}
  env:
    description: 'environment of the container'
    value: ${{ steps.set-output.outputs.env }}

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Check COPY . . in Dockerfile
    run: |
      if grep -q "COPY.*\. \." ${{ inputs.WORKING_DIRECTORY }}/Dockerfile; then
        echo "COPY . . is not allowed in Dockerfile"
        exit 1
      fi
    shell: bash

  - name: Login to Github Registry
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: ${{ github.repository_owner }}
      password: ${{ inputs.GITHUB_TOKEN }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  # - name: get-npm-version
  #   id: package-version
  #   uses: martinbeentjes/npm-get-version-action@main

  - name: get-npm-version
    id: package-version
    run: |
      PACKAGE_VERSION=$(cat ${{ inputs.WORKING_DIRECTORY }}/package.json | jq '.version' | tr -d '"')
      echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
    shell: bash

  - name: Build Container name for develop
    if: github.ref == 'refs/heads/develop'
    run: |
      echo "IMAGE_TAG=dev" >> $GITHUB_ENV
      echo "ENV=stage" >> $GITHUB_ENV
    shell: bash

  - name: Build Container name for master
    if: github.ref != 'refs/heads/develop'
    run: |
      echo "IMAGE_TAG=${{ steps.package-version.outputs.current-version}}" >> $GITHUB_ENV
      echo "ENV=prod" >> $GITHUB_ENV
    shell: bash

  - name: Check file existence (next)
    id: check_files_next
    uses: andstor/file-existence-action@v2
    with:
      files: '${{ inputs.WORKING_DIRECTORY }}/.env.production, ${{ inputs.WORKING_DIRECTORY }}/next.config.*'
  
  - name: Check file existence (astro)
    id: check_files_astro
    uses: andstor/file-existence-action@v2
    with:
      files: '${{ inputs.WORKING_DIRECTORY }}/.env.production, ${{ inputs.WORKING_DIRECTORY }}/astro.config.mjs'

  - name: Remove production environment file on develop for next/astro projects
    if: github.ref == 'refs/heads/develop' && (steps.check_files_next.outputs.files_exists == 'true' || steps.check_files_astro.outputs.files_exists == 'true')
    run: |
      rm -f ${{ inputs.WORKING_DIRECTORY }}/.env.production
    shell: bash

  - name: Setup database
    if: inputs.TESTING_WITH_DB == 'true'
    run: |
      if command -v docker &> /dev/null
      then
          cat ${{ inputs.DB_CREATE_FILEPATH }} | docker run -e PGPASSWORD=$PGPASSWORD --network host --rm -i postgres psql -h localhost -U postgres -d hectorone
      else
          if command -v psql &> /dev/null
          then
              cat ${{ inputs.DB_CREATE_FILEPATH }} | psql -h localhost -U postgres -d hectorone
          else
              echo "Neither docker nor psql is installed. Please install one of them."
              exit 1
          fi
      fi
    env:
      PGPASSWORD: password
    shell: bash

  - name: Setup testdata
    if: inputs.DB_TESTDATA_FILEPATH != 'false'
    run: |
      if command -v docker &> /dev/null
      then
          cat ${{ inputs.DB_TESTDATA_FILEPATH }} | docker run -e PGPASSWORD=$PGPASSWORD --network host --rm -i postgres psql -h localhost -U postgres -d hectorone
      else
          if command -v psql &> /dev/null
          then
              cat ${{ inputs.DB_TESTDATA_FILEPATH }} | psql -h localhost -U postgres -d hectorone
          else
              echo "Neither docker nor psql is installed. Please install one of them."
              exit 1
          fi
      fi
    env:
      PGPASSWORD: password
    shell: bash
      
# TODO add WORKING_DIRECTORY
  - name: Write local-testing config file
    if: inputs.LOCAL_TESTING_SECRET != 'false'
    uses: 'DamianReeves/write-file-action@master'
    with:
      path: config/local.yaml
      contents: |
        ${{ inputs.LOCAL_TESTING_SECRET }}

  - name: Set up docker buildx for tester
    if: inputs.ACTION_ENABLE_TESTING == 'true' || inputs.TESTING_WITH_DB == 'true'
    id: tester
    uses: docker/build-push-action@v3
    with:
      context: ${{ inputs.WORKING_DIRECTORY }}
      file: ${{ inputs.WORKING_DIRECTORY }}/Dockerfile
      push: true
      target: tester
      platforms: linux/amd64
      network: host # ?
      tags: ghcr.io/entrecode/${{ inputs.NAMESPACE }}.${{ inputs.NAME}}:tester
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: |
        PAT=${{ inputs.PAT }}

  - name: Test
    if: (inputs.ACTION_ENABLE_TESTING == 'true' || inputs.TESTING_WITH_DB == 'true') && steps.tester.outcome == 'success'
    id: testrunner
    run: |
      docker run --network="host" --rm ghcr.io/entrecode/${{ inputs.NAMESPACE }}.${{ inputs.NAME}}:tester
    shell: bash

# TODO add WORKING_DIRECTORY
  - name: Remove local testing file
    if: inputs.LOCAL_TESTING_SECRET != 'false'
    run: |
      rm -f config/local-testing.yaml
    shell: bash

  - name: Build and push
    if: (inputs.ACTION_ENABLE_TESTING == 'false' && inputs.TESTING_WITH_DB == 'false' || steps.testrunner.outcome == 'success') && inputs.ACTIVATE_DEV_RUNNER == 'true' && github.ref == 'refs/heads/develop'
    uses: docker/build-push-action@v3
    with:
      context: ${{ inputs.WORKING_DIRECTORY }}
      file: ${{ inputs.WORKING_DIRECTORY }}/Dockerfile
      push: true
      target: devRunner
      platforms: linux/amd64
      tags: ghcr.io/entrecode/${{ inputs.NAMESPACE }}.${{ inputs.NAME}}:${{ env.IMAGE_TAG }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: |
        PAT=${{ inputs.PAT }}

  - name: Build and push
    if: ((inputs.ACTION_ENABLE_TESTING == 'false' && inputs.TESTING_WITH_DB == 'false' || steps.testrunner.outcome == 'success') && inputs.ACTIVATE_DEV_RUNNER == 'false') || ((inputs.ACTION_ENABLE_TESTING == 'false' && inputs.TESTING_WITH_DB == 'false' || steps.testrunner.outcome == 'success') && inputs.ACTIVATE_DEV_RUNNER == 'true' && github.ref != 'refs/heads/develop')
    uses: docker/build-push-action@v3
    with:
      context: ${{ inputs.WORKING_DIRECTORY }}
      file: ${{ inputs.WORKING_DIRECTORY }}/Dockerfile
      push: true
      target: runner
      platforms: linux/amd64
      tags: ghcr.io/entrecode/${{ inputs.NAMESPACE }}.${{ inputs.NAME}}:${{ env.IMAGE_TAG }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: |
        PAT=${{ inputs.PAT }}

  - name: Set output
    id: set-output
    run: |
      echo "version=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
      echo "env=${{ env.ENV }}" >> $GITHUB_OUTPUT
    shell: bash
